fridge_tracker/config/routes.rb
Rails.application.routes.draw do
  get 'fridge/index'
  post 'fridge/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

fridge_tracker/app/models/fridge.rb
class Fridge < ApplicationRecord
end

fridge_tracker/app/controllers/fridge_controller.rb
class FridgeController < ApplicationController
  def index
   @fridges = Fridge.all
   @new_fridge = Fridge.new
  end

  def new

    @new_location = (params[:fridge][:location])  
    @new_brand = (params[:fridge][:brand])  
    @new_size = (params[:fridge][:size])  

    @new_fridge = Fridge.new(location: @new_location, brand: @new_brand, size: @new_size)

    if @new_fridge.save
      # success
      redirect_back(fallback_location: @index)
    else
      # error handling
    end  
  end
end

fridge_tracker/app/helpers/fridge_helper.rb
module FridgeHelper
end

fridge_tracker/app/views/fridge/index.html.erb
<h1>These are the Fridges</h1>

<% @fridges.each do |fridge| %>
<ul>
  <li>Fridge: <%= fridge.location %></li>
</ul>
<% end %>


<%= form_for @new_fridge, url: fridge_new_path(@new_fridge) do |f| %>
    <%= f.label :location %>
    <%= f.text_field :location %>
    <%= f.label :brand %>
    <%= f.text_field :brand %>
    <%= f.label :size %>
    <%= f.text_field :size %>
    <%=f.submit%>
<% end %>

fridge_tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FridgeTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>